- name: copy elastic repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic/repo

- name: Install FileBeat
  ansible.builtin.yum:
    name: filebeat
    state: installed

- name: copy filebeat config file
  ansible.builtin.template:
    src: filebeat1.yml
    dest: /etc/filebeat/filebeat.yml
