- name: copy logstash conf file
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restart Logstatsh
  ansible.builtin.systemd:
    name: logstash
    state: restarted
    enabled: true
