- name: dummy
  ansible.builtin.debug:
    msg: hello component-dispatch

- name: calling golang function
  ansible.builtin.import_role:
    name: common
    tasks_from: golang

- name: Import Prometheus
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter