- name: Add Application User
  ansible.builtin.user:
    name: "{{app_user}}"

- name: Remove Application Directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create Application Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Unarchive & Download Application files
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes
