- name: dummy
  ansible.builtin.debug:
    msg: hello component-cart

- name: calling nodejs function
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Import Prometheus
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter



#  print_head calling nodejs function
#  component=cart
#  func_nodejs